# Generated by Django 5.1.3 on 2026-06-18 05:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('scheduled_time', models.DateTimeField(db_index=True, help_text='When this event is scheduled to occur.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fired', 'Fired')], db_index=True, default='pending', max_length=16)),
                ('fired_at', models.DateTimeField(blank=True, help_text='Actual time the event was fired (null until fired).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['scheduled_time'],
                'indexes': [models.Index(fields=['status', 'scheduled_time'], name='notificatio_status_b3b9b2_idx')],
            },
        ),
    ]
