# Generated by Django 5.1.3 on 2026-06-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dispatch_task_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text="Celery id of the one-shot fire_event task armed for this event's scheduled_time. Non-null means the event is already armed; cleared when the event is re-timed so the scheduler can re-arm it.", max_length=255, null=True),
        ),
    ]
