# Generated by Django 5.1.3 on 2026-06-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_event_dispatch_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('fired', 'Fired')], db_index=True, default='pending', max_length=16),
        ),
    ]
