# Generated by Django 5.1.3 on 2026-06-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dispatch_task_id',
            field=models.CharField(blank=True, editable=False, help_text='Celery id of the one-shot fire_event task armed while this event is SCHEDULED, kept so the task can be revoked if the event is re-timed. Never queried — arming/firing key off status — so it carries no index.', max_length=255, null=True),
        ),
    ]
