# Generated by Django 5.1.3 on 2026-06-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_event_dispatch_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dispatch_task_id',
            field=models.CharField(blank=True, editable=False, help_text="Name of the one-off clocked fire_event PeriodicTask armed while this event is SCHEDULED (deterministically 'fire-event-<id>'). Stored for inspectability/rollback; the row is keyed by name, not this column.", max_length=255, null=True),
        ),
    ]
